
// Objective-C API for talking to the following Go packages
//
//	github.com/numa08/Turkey/tello
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Tello_FRAMEWORK_H__
#define __Tello_FRAMEWORK_H__

#include "Tello.objc.h"
#include "universe.objc.h"

#endif
